-- data table merchant

INSERT INTO merchant (name, no_telephon, category, balance, created_at, updated_at)
VALUES ('ACT', '01112', 'fashion', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO merchant (name, no_telephon, category, balance, created_at, updated_at)
VALUES ('JatiPermata', '01113', 'furniture', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO merchant (name, no_telephon, category, balance, created_at, updated_at)
VALUES ('BeautyQ', '01114', 'Make-up', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO merchant (name, no_telephon, category, balance, created_at, updated_at)
VALUES ('GuySensey', '01115', 'gym-tools', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO customer (name, email, password, balance, created_at, updated_at)
VALUES ('Agus', 'agus@mail.com', 'agus1234', 500000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO customer (name, email, password, balance, created_at, updated_at)
VALUES ('Agung', 'agung@mail.com', 'agung1234', 500000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO customer (name, email, password, balance, created_at, updated_at)
VALUES ('Agam', 'agam@mail.com', 'agam1234', 500000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);