-- data table merchant

INSERT INTO merchant (name, no_telephon, category, balance, created_at, updated_at)
VALUES ('ACT', '01112', 'fashion', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO merchant (name, no_telephon, category, balance, created_at, updated_at)
VALUES ('JatiPermata', '01113', 'furniture', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO merchant (name, no_telephon, category, balance, created_at, updated_at)
VALUES ('BeautyQ', '01114', 'Make-up', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO merchant (name, no_telephon, category, balance, created_at, updated_at)
VALUES ('GuySensey', '01115', 'gym-tools', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
